#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
    compare = [0, 0];
    for item in range(len(a)):
        if a[item] > b[item]:
            compare[0] = compare[0] + 1;
        if a[item] < b[item]:
            compare[1] = compare[1] + 1;
    return compare;

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
