#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    minValue = 0;
    maxValue = 0;
    arr.sort();
    for i in range(len(arr) - 1):
        minValue += arr[i];
        maxValue += arr[i + 1];
    print(minValue, maxValue)

if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
