#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    line = "";
    for i in range(n):
        for j in range(n - 1 - i):
            line = line + " ";
        for j in range(i+1):
            line = line + "#";
        print(line)
        line = "";
    


if __name__ == '__main__':
    n = int(input())

    staircase(n)
